### ISSUE TITLE
Scheduler has rare segfault

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#207]
Logs from prod:

```
I0420 01:11:04.718532       1 plugin.go:707] [autoscale-enforcer] Unreserve: Handling request for pod default/[REDACTED], node ip-10-8-28-167.us-east-2.compute.internal
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x19e0094]

goroutine 909 [running]:
github.com/neondatabase/autoscaling/pkg/plugin.(*AutoscaleEnforcer).Unreserve(0xc00020f480, {0xc000597f20?, 0xc002703f20?}, 0xc002703f20?, 0xc00309fc00, {0xc0027a50b0, 0x28})
	/workspace/pkg/plugin/plugin.go:733 +0x734
k8s.io/kubernetes/pkg/scheduler/framework/runtime.(*frameworkImpl).runReservePluginUnreserve(0xc002703f20?, {0x225bd10?, 0xc001e4b1c0?}, {0x7f6d31f17b20?, 0xc00020f480?}, 0x0?, 0xad4706?, {0xc0027a50b0?, 0x40f827?})
	/go/pkg/mod/k8s.io/kubernetes@v1.23.15/pkg/scheduler/framework/runtime/framework.go:1137 +0x2bb
k8s.io/kubernetes/pkg/scheduler/framework/runtime.(*frameworkImpl).RunReservePluginsUnreserve(0xc00032d500, {0x225bd10, 0xc001e4b1c0}, 0x13?, 0xc00032d500?, {0xc0027a50b0, 0x28})
	/go/pkg/mod/k8s.io/kubernetes@v1.23.15/pkg/scheduler/framework/runtime/framework.go:1131 +0x12b
k8s.io/kubernetes/pkg/scheduler.(*Scheduler).scheduleOne.func1()
	/go/pkg/mod/k8s.io/kubernetes@v1.23.15/pkg/scheduler/scheduler.go:610 +0x7ae
created by k8s.io/kubernetes/pkg/scheduler.(*Scheduler).scheduleOne
	/go/pkg/mod/k8s.io/kubernetes@v1.23.15/pkg/scheduler/scheduler.go:553 +0x118a
```

Edit 2023-07-10: At the time that happened, the scheduler was v0.6.0.
`pkg/plugin/plugin.go:733` was:

https://github.com/neondatabase/autoscaling/blob/73748102420e03d414a17f7da5b8f7834d687a50/pkg/plugin/plugin.go#L733

**Comment by sharnoff** [comment]
This happened again on staging (🤯)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1ac539d]

goroutine 171 [running]:
github.com/neondatabase/autoscaling/pkg/plugin.(*AutoscaleEnforcer).handleNodeDeletion(0xc0001b7740, 0x1aded29?, {0xc001891170, 0x2e})
	/workspace/pkg/plugin/state.go:717 +0x47d
github.com/neondatabase/autoscaling/pkg/plugin.makeAutoscaleEnforcerPlugin.func2.1()
	/workspace/pkg/plugin/plugin.go:129 +0x29
github.com/neondatabase/autoscaling/pkg/plugin.makeAutoscaleEnforcerPlugin.func10()
	/workspace/pkg/plugin/plugin.go:196 +0xa4
created by github.com/neondatabase/autoscaling/pkg/plugin.makeAutoscaleEnforcerPlugin
	/workspace/pkg/plugin/plugin.go:192 +0xf7e
```

Time: approx `2023-07-08 08:47:41 UTC`
Region: `dev-eu-west-1-zeta`
Pod name: `autoscale-scheduler-b67bb55c7-6vhzp`

**Comment by sharnoff** [comment]
Oh, and actually there's another one from prod as well:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1ac539d]

goroutine 354 [running]:
github.com/neondatabase/autoscaling/pkg/plugin.(*AutoscaleEnforcer).handleNodeDeletion(0xc0002b3080, 0x1aded29?, {0xc003abb6b0, 0x2d})
	/workspace/pkg/plugin/state.go:717 +0x47d
github.com/neondatabase/autoscaling/pkg/plugin.makeAutoscaleEnforcerPlugin.func2.1()
	/workspace/pkg/plugin/plugin.go:129 +0x29
github.com/neondatabase/autoscaling/pkg/plugin.makeAutoscaleEnforcerPlugin.func10()
	/workspace/pkg/plugin/plugin.go:196 +0xa4
created by github.com/neondatabase/autoscaling/pkg/plugin.makeAutoscaleEnforcerPlugin
	/workspace/pkg/plugin/plugin.go:192 +0xf7e
```

(same location as previous comment)

Time: approx `2023-07-10 11:07:59 UTC`
Region: `prod-ap-southeast-1-epsilon`
Pod name: `autoscale-scheduler-b67bb55c7-bk78l`

**Comment by vadim2404** [comment]
@sharnoff to update the status

**Comment by sharnoff** [comment]
I don't currently see this on staging/prod, but this was quite rare before, and the logs only go back a few weeks.
IMO we should check back in 2 weeks, then 2 weeks after, and it's still not shown up again, we can close.

**Comment by sharnoff** [comment]
Update: Still don't see any occurrences in prod.
If still not present in 2 weeks, will close.

**Comment by sharnoff** [comment]
Still don't see this, closing the issue.

Only thing I saw was [one compute ID](https://neondb.slack.com/archives/C02712LTZKQ/p1706676965575079) that contains `panic` in its name 😅
